fragment userCurrentTaskbarItemAttributes on UserTaskbarItem {
  id
  key
  callback
  formId
  formNewArticlePresent
  entity {
    __typename
    ... on Ticket {
      ...ticketTaskbarTabAttributes
    }
    ... on KnowledgeBaseAnswerTranslation {
      ...knowledgeBaseAnswerTaskbarTabAttributes
    }
    ... on UserTaskbarItemEntityTicketCreate {
      uid
      title
      createArticleTypeKey
    }
    ... on UserTaskbarItemEntityKnowledgeBaseAnswerCreate {
      uid
      title
      locale
      visibility
    }
    ... on UserTaskbarItemEntitySearch {
      query
      model
      filters
      filterCount
    }
    ... on User {
      id
      internalId
      fullname
      active
    }
    ... on Organization {
      id
      internalId
      name
      active
    }
  }
  entityAccess
  prio
  changed
  dirty
  notify
  updatedAt
}
