name: zammad
description: Zammad is a web based open source helpdesk/customer support system
homepage: https://zammad.org
notifications: false
targets:
  centos-7:
    dependencies:
      - elasticsearch
      - nginx
      - postgresql-server
      - which
  debian-8:
    dependencies:
      - elasticsearch
      - nginx|apache2
      - postgresql|mysql-server|mariadb-server|sqlite
  debian-9:
    dependencies:
      - elasticsearch
      - nginx|apache2
      - postgresql|mariadb-server|sqlite      
  ubuntu-16.04:
    dependencies:
      - elasticsearch
      - nginx|apache2
      - postgresql|mysql-server|mariadb-server|sqlite
  sles-12:
    dependencies:
      - elasticsearch
      - nginx
      - postgresql-server
before:
  - uname -a
  - ruby -v
  - env
  - "cat Gemfile.lock"
  - contrib/cleanup.sh
after:
  - contrib/packager.io/after.sh
env:
  - RAILS_ENV=production
  - ZAMMAD_BIND_IP=127.0.0.1
  - ZAMMAD_RAILS_PORT=3000
  - ZAMMAD_WEBSOCKET_PORT=6042
services:
  - postgres
after_install: contrib/packager.io/postinstall.sh
