targets:
  centos-6:
    dependencies:
      - httpd
      - postgresql
      - postgresql-server
      - postgresql-devel
  centos-7:
    dependencies:
      - httpd
      - postgresql
      - postgresql-server
      - postgresql-devel

before:
  - uname -a
  - ruby -v
  - env
  - cp config/database.yml.pkgr config/database.yml
  - echo "gem 'pg'" >> Gemfile.local
  - echo "gem 'mysql2', '~> 0.3.20'" >> Gemfile.local
  - sed -i "s/specs:/specs:\\n    pg (0.18.4)/g" Gemfile.lock
  - sed -i "s/DEPENDENCIES/DEPENDENCIES\\n  pg/g" Gemfile.lock
  - "#cat Gemfile.lock"
  - contrib/cleanup.sh

env:
  - RAILS_ENV=production
  - PORT=3000
  - RAILS_SERVE_STATIC_FILES=true

services:
  - postgres

notifications: false
