name: zammad
description: Zammad is a web based open source helpdesk/customer support system
homepage: https://zammad.org
notifications: false
targets:
  centos-7:
    dependencies:
      - curl
      - elasticsearch
      - nginx
      - postgresql-server
      - which
      - epel-release
      - imlib2
      - imlib2-devel
    build_dependencies:
      - http://download.fedoraproject.org/pub/epel/7/x86_64/Packages/i/imlib2-1.4.5-9.el7.x86_64.rpm
      - http://download.fedoraproject.org/pub/epel/7/x86_64/Packages/i/imlib2-devel-1.4.5-9.el7.x86_64.rpm
  centos-8:
    dependencies:
      - curl
      - elasticsearch
      - nginx
      - postgresql-server
      - which
      - epel-release
      - imlib2
      - imlib2-devel
    build_dependencies:
      - http://download.fedoraproject.org/pub/epel/8/Everything/x86_64/Packages/i/imlib2-1.4.9-8.el8.x86_64.rpm
      - http://download.fedoraproject.org/pub/epel/8/Everything/x86_64/Packages/i/imlib2-devel-1.4.9-8.el8.x86_64.rpm
  debian-8:
    dependencies:
      - curl
      - elasticsearch
      - nginx|apache2
      - postgresql|mysql-server|mariadb-server|sqlite
      - libimlib2
      - libimlib2-dev
    build_dependencies:
      - libimlib2
      - libimlib2-dev
  debian-9:
    dependencies:
      - curl
      - elasticsearch
      - nginx|apache2
      - postgresql|mariadb-server|sqlite
      - libimlib2
      - libimlib2-dev
    build_dependencies:
      - libimlib2
      - libimlib2-dev
  debian-10:
    dependencies:
      - curl
      - elasticsearch
      - nginx|apache2
      - postgresql|mariadb-server|sqlite
      - libimlib2
      - libimlib2-dev
    build_dependencies:
      - libimlib2
      - libimlib2-dev
  ubuntu-16.04:
    dependencies:
      - curl
      - elasticsearch
      - nginx|apache2
      - postgresql|mysql-server|mariadb-server|sqlite
      - libimlib2
      - libimlib2-dev
    build_dependencies:
      - libimlib2
      - libimlib2-dev
  ubuntu-18.04:
    dependencies:
      - curl
      - elasticsearch
      - nginx|apache2
      - postgresql|mysql-server|mariadb-server|sqlite
      - libimlib2
      - libimlib2-dev
    build_dependencies:
      - libimlib2
      - libimlib2-dev
  ubuntu-20.04:
    dependencies:
      - curl
      - elasticsearch
      - nginx|apache2
      - postgresql|mysql-server|mariadb-server|sqlite
      - libimlib2
      - libimlib2-dev
    build_dependencies:
      - libimlib2
      - libimlib2-dev
  sles-12:
    dependencies:
      - curl
      - elasticsearch
      - nginx
      - postgresql-server
      - imlib2
      - libImlib2-1
      - imlib2
      - imlib2-devel
    build_dependencies:
      - https://ftp.gwdg.de/pub/opensuse/discontinued/distribution/12.3/repo/oss/suse/x86_64/imlib2-1.4.5-12.1.1.x86_64.rpm
      - https://ftp.gwdg.de/pub/opensuse/discontinued/distribution/12.3/repo/oss/suse/x86_64/imlib2-devel-1.4.5-12.1.1.x86_64.rpm
      - https://ftp.gwdg.de/pub/opensuse/discontinued/distribution/12.3/repo/oss/suse/x86_64/imlib2-filters-1.4.5-12.1.1.x86_64.rpm
      - https://ftp.gwdg.de/pub/opensuse/discontinued/distribution/12.3/repo/oss/suse/x86_64/libImlib2-1-1.4.5-12.1.1.x86_64.rpm
before:
  - contrib/packager.io/before.sh
after:
  - contrib/packager.io/after.sh
env:
  - RAILS_ENV=production
  - ZAMMAD_BIND_IP=127.0.0.1
  - ZAMMAD_RAILS_PORT=3000
  - ZAMMAD_WEBSOCKET_PORT=6042
services:
  - postgres
after_install: contrib/packager.io/postinstall.sh
