---
allowBuilds:
  core-js-pure: true
  esbuild: true
  unrs-resolver: true
  vue-demi: true
minimumReleaseAgeExclude:
  - '@vitest/mocker@5.0.0'
  - '@vitest/spy@5.0.0'
  - vitest@5.0.0
overrides:
  '@sa11y/vitest>vitest': ^5.0.0
verifyDepsBeforeRun: false
