mutation ticketArticleTranslateMany(
  $ticketId: ID!
  $firstArticlesCount: Int
  $loadFirstArticles: Boolean
  $pageSize: Int
  $beforeCursor: String
  $afterCursor: String
  $targetLocale: String!
  $generateMissing: Boolean!
) {
  ticketArticleTranslateMany(
    ticketId: $ticketId
    firstArticlesCount: $firstArticlesCount
    loadFirstArticles: $loadFirstArticles
    pageSize: $pageSize
    beforeCursor: $beforeCursor
    afterCursor: $afterCursor
    targetLocale: $targetLocale
    generateMissing: $generateMissing
  ) {
    pendingArticleIds @include(if: $generateMissing)
    results {
      article {
        ...ticketArticleTranslationAvailability
        ...ticketArticleTranslation @include(if: $generateMissing)
      }
      translated @include(if: $generateMissing)
    }
  }
}
