ARG DISTRIBUTION_VERSION
FROM docker.io/library/ubuntu:${DISTRIBUTION_VERSION}
ARG DISTRIBUTION
ARG DISTRIBUTION_VERSION
ARG CI_COMMIT_REF_NAME
ADD dockerfiles dockerfiles
ADD scenarios scenarios
RUN bash /dockerfiles/bootstrap.ubuntu.sh
ENTRYPOINT [ "/sbin/init" ]