ARG DISTRIBUTION_VERSION
FROM docker.io/library/debian:${DISTRIBUTION_VERSION}
ARG DISTRIBUTION
ARG DISTRIBUTION_VERSION
ARG CI_COMMIT_REF_NAME
ADD dockerfiles dockerfiles
ADD scenarios scenarios
RUN bash /dockerfiles/bootstrap.debian.sh
ENTRYPOINT [ "/sbin/init" ]