#!/usr/bin/env bash
# Automatic documentation generation from commit messages

set -o pipefail

echo "Generating documentation from commit messages..."

# Check if we're in a PR context
if [ -z "$GITHUB_BASE_REF" ]; then
  echo "Not in a PR context, skipping documentation generation"
  exit 0
fi

BASE_BRANCH="${GITHUB_BASE_REF}"
DOC_FILE="PR_DOCUMENTATION.md"

echo "Analyzing commits from base branch: $BASE_BRANCH"

# Get commit range
git fetch origin "$BASE_BRANCH" --depth=50 2>/dev/null || true
MERGE_BASE=$(git merge-base origin/"$BASE_BRANCH" HEAD 2>/dev/null || echo "origin/$BASE_BRANCH")

# Generate documentation header
cat > "$DOC_FILE" << EOF
# Pull Request Documentation

**Generated from commit messages**
**Date**: $(date -u '+%Y-%m-%d %H:%M:%S UTC')

---

## Summary

This document was automatically generated by analyzing the commit messages in this pull request.

EOF

# Count commits
COMMIT_COUNT=$(git rev-list --count "$MERGE_BASE..HEAD" 2>/dev/null || echo "0")
echo "**Total Commits**: $COMMIT_COUNT" >> "$DOC_FILE"
echo "" >> "$DOC_FILE"

# Analyze commit types
echo "## Commit Analysis" >> "$DOC_FILE"
echo "" >> "$DOC_FILE"

# Extract commit messages and categorize
FEATURES=$(git log --format="%s" "$MERGE_BASE..HEAD" 2>/dev/null | grep -i "^feature:\|^feat:" | wc -l)
FIXES=$(git log --format="%s" "$MERGE_BASE..HEAD" 2>/dev/null | grep -i "^fix:\|^bugfix:" | wc -l)
DOCS=$(git log --format="%s" "$MERGE_BASE..HEAD" 2>/dev/null | grep -i "^docs:\|^doc:" | wc -l)
TESTS=$(git log --format="%s" "$MERGE_BASE..HEAD" 2>/dev/null | grep -i "^test:\|^tests:" | wc -l)
REFACTOR=$(git log --format="%s" "$MERGE_BASE..HEAD" 2>/dev/null | grep -i "^refactor:" | wc -l)
CHORE=$(git log --format="%s" "$MERGE_BASE..HEAD" 2>/dev/null | grep -i "^chore:" | wc -l)

echo "### Commit Type Breakdown" >> "$DOC_FILE"
echo "" >> "$DOC_FILE"
echo "| Type | Count |" >> "$DOC_FILE"
echo "|------|-------|" >> "$DOC_FILE"
echo "| 🎉 Features | $FEATURES |" >> "$DOC_FILE"
echo "| 🐛 Bug Fixes | $FIXES |" >> "$DOC_FILE"
echo "| 📖 Documentation | $DOCS |" >> "$DOC_FILE"
echo "| ✅ Tests | $TESTS |" >> "$DOC_FILE"
echo "| ♻️  Refactoring | $REFACTOR |" >> "$DOC_FILE"
echo "| 🔧 Chores | $CHORE |" >> "$DOC_FILE"
echo "" >> "$DOC_FILE"

# List all commits with categorization
echo "## Detailed Commit List" >> "$DOC_FILE"
echo "" >> "$DOC_FILE"

# Function to categorize and format commit
categorize_commit() {
  local msg="$1"
  local icon="📝"

  if echo "$msg" | grep -iq "^feature:\|^feat:"; then
    icon="🎉"
  elif echo "$msg" | grep -iq "^fix:\|^bugfix:"; then
    icon="🐛"
  elif echo "$msg" | grep -iq "^docs:\|^doc:"; then
    icon="📖"
  elif echo "$msg" | grep -iq "^test:\|^tests:"; then
    icon="✅"
  elif echo "$msg" | grep -iq "^refactor:"; then
    icon="♻️"
  elif echo "$msg" | grep -iq "^chore:"; then
    icon="🔧"
  elif echo "$msg" | grep -iq "^perf:\|^performance:"; then
    icon="⚡"
  elif echo "$msg" | grep -iq "^style:"; then
    icon="💄"
  elif echo "$msg" | grep -iq "^build:"; then
    icon="🏗️"
  elif echo "$msg" | grep -iq "^ci:"; then
    icon="👷"
  fi

  echo "$icon"
}

# Get commit log with details
git log --format="%H|%s|%an|%ar" "$MERGE_BASE..HEAD" 2>/dev/null | while IFS='|' read -r hash subject author date; do
  icon=$(categorize_commit "$subject")
  echo "### $icon $subject" >> "$DOC_FILE"
  echo "" >> "$DOC_FILE"
  echo "- **Author**: $author" >> "$DOC_FILE"
  echo "- **Date**: $date" >> "$DOC_FILE"
  echo "- **Commit**: \`${hash:0:7}\`" >> "$DOC_FILE"

  # Get full commit message body
  BODY=$(git log -1 --format="%b" "$hash" 2>/dev/null)
  if [ -n "$BODY" ]; then
    echo "" >> "$DOC_FILE"
    echo "<details><summary>Commit Details</summary>" >> "$DOC_FILE"
    echo "" >> "$DOC_FILE"
    echo '```' >> "$DOC_FILE"
    echo "$BODY" >> "$DOC_FILE"
    echo '```' >> "$DOC_FILE"
    echo "</details>" >> "$DOC_FILE"
  fi
  echo "" >> "$DOC_FILE"
done

# Analyze file changes
echo "## File Changes" >> "$DOC_FILE"
echo "" >> "$DOC_FILE"

FILES_CHANGED=$(git diff --name-only "$MERGE_BASE..HEAD" 2>/dev/null | wc -l)
ADDITIONS=$(git diff --shortstat "$MERGE_BASE..HEAD" 2>/dev/null | grep -oP '\d+(?= insertion)' || echo "0")
DELETIONS=$(git diff --shortstat "$MERGE_BASE..HEAD" 2>/dev/null | grep -oP '\d+(?= deletion)' || echo "0")

echo "- **Files Changed**: $FILES_CHANGED" >> "$DOC_FILE"
echo "- **Lines Added**: $ADDITIONS" >> "$DOC_FILE"
echo "- **Lines Deleted**: $DELETIONS" >> "$DOC_FILE"
echo "" >> "$DOC_FILE"

# Categorize changed files
echo "### Changed Files by Type" >> "$DOC_FILE"
echo "" >> "$DOC_FILE"

RUBY_FILES=$(git diff --name-only "$MERGE_BASE..HEAD" 2>/dev/null | grep '\.rb$' | wc -l)
JS_FILES=$(git diff --name-only "$MERGE_BASE..HEAD" 2>/dev/null | grep '\.js$\|\.ts$\|\.vue$' | wc -l)
SPEC_FILES=$(git diff --name-only "$MERGE_BASE..HEAD" 2>/dev/null | grep '_spec\.rb$\|\.spec\.' | wc -l)
DOC_FILES=$(git diff --name-only "$MERGE_BASE..HEAD" 2>/dev/null | grep '\.md$' | wc -l)
CONFIG_FILES=$(git diff --name-only "$MERGE_BASE..HEAD" 2>/dev/null | grep '\.yml$\|\.yaml$\|\.json$' | wc -l)

echo "| File Type | Count |" >> "$DOC_FILE"
echo "|-----------|-------|" >> "$DOC_FILE"
echo "| Ruby Files | $RUBY_FILES |" >> "$DOC_FILE"
echo "| JavaScript/TypeScript/Vue | $JS_FILES |" >> "$DOC_FILE"
echo "| Test/Spec Files | $SPEC_FILES |" >> "$DOC_FILE"
echo "| Documentation | $DOC_FILES |" >> "$DOC_FILE"
echo "| Configuration | $CONFIG_FILES |" >> "$DOC_FILE"
echo "" >> "$DOC_FILE"

# Generate suggested CHANGELOG entry
echo "## Suggested CHANGELOG Entry" >> "$DOC_FILE"
echo "" >> "$DOC_FILE"
echo '```markdown' >> "$DOC_FILE"
echo "### $(date '+%Y-%m-%d')" >> "$DOC_FILE"
echo "" >> "$DOC_FILE"

# Group by type
if [ "$FEATURES" -gt 0 ]; then
  echo "#### Features" >> "$DOC_FILE"
  git log --format="- %s" "$MERGE_BASE..HEAD" 2>/dev/null | grep -i "^- feature:\|^- feat:" >> "$DOC_FILE" || true
  echo "" >> "$DOC_FILE"
fi

if [ "$FIXES" -gt 0 ]; then
  echo "#### Bug Fixes" >> "$DOC_FILE"
  git log --format="- %s" "$MERGE_BASE..HEAD" 2>/dev/null | grep -i "^- fix:\|^- bugfix:" >> "$DOC_FILE" || true
  echo "" >> "$DOC_FILE"
fi

if [ "$DOCS" -gt 0 ]; then
  echo "#### Documentation" >> "$DOC_FILE"
  git log --format="- %s" "$MERGE_BASE..HEAD" 2>/dev/null | grep -i "^- docs:\|^- doc:" >> "$DOC_FILE" || true
  echo "" >> "$DOC_FILE"
fi

echo '```' >> "$DOC_FILE"
echo "" >> "$DOC_FILE"

# Migration detection
MIGRATIONS=$(git diff --name-only "$MERGE_BASE..HEAD" 2>/dev/null | grep '^db/migrate/' | wc -l)
if [ "$MIGRATIONS" -gt 0 ]; then
  echo "## ⚠️  Database Migrations Detected" >> "$DOC_FILE"
  echo "" >> "$DOC_FILE"
  echo "This PR includes $MIGRATIONS database migration(s):" >> "$DOC_FILE"
  echo "" >> "$DOC_FILE"
  git diff --name-only "$MERGE_BASE..HEAD" 2>/dev/null | grep '^db/migrate/' | while read -r migration; do
    echo "- \`$migration\`" >> "$DOC_FILE"
  done
  echo "" >> "$DOC_FILE"
  echo "**Action Required**: Run \`rails db:migrate\` after merging." >> "$DOC_FILE"
  echo "" >> "$DOC_FILE"
fi

# Breaking changes detection
BREAKING=$(git log --format="%s %b" "$MERGE_BASE..HEAD" 2>/dev/null | grep -i "breaking\|breaking change" | wc -l)
if [ "$BREAKING" -gt 0 ]; then
  echo "## ⚠️  Breaking Changes Detected" >> "$DOC_FILE"
  echo "" >> "$DOC_FILE"
  echo "This PR may contain breaking changes. Review carefully before merging." >> "$DOC_FILE"
  echo "" >> "$DOC_FILE"
  git log --format="%s" "$MERGE_BASE..HEAD" 2>/dev/null | grep -i "breaking" | while read -r change; do
    echo "- $change" >> "$DOC_FILE"
  done
  echo "" >> "$DOC_FILE"
fi

# Footer
echo "---" >> "$DOC_FILE"
echo "" >> "$DOC_FILE"
echo "*This documentation was automatically generated from commit messages.*" >> "$DOC_FILE"
echo "*Please review and update as needed.*" >> "$DOC_FILE"

echo "✅ Documentation generated: $DOC_FILE"

# Output summary to GitHub Step Summary
if [ -n "$GITHUB_STEP_SUMMARY" ]; then
  echo "## 📖 Auto-Generated Documentation" >> "$GITHUB_STEP_SUMMARY"
  echo "" >> "$GITHUB_STEP_SUMMARY"
  echo "Documentation has been automatically generated from commit messages." >> "$GITHUB_STEP_SUMMARY"
  echo "" >> "$GITHUB_STEP_SUMMARY"
  echo "- Commits analyzed: $COMMIT_COUNT" >> "$GITHUB_STEP_SUMMARY"
  echo "- Features: $FEATURES" >> "$GITHUB_STEP_SUMMARY"
  echo "- Bug fixes: $FIXES" >> "$GITHUB_STEP_SUMMARY"
  echo "- Documentation: $DOCS" >> "$GITHUB_STEP_SUMMARY"

  if [ "$MIGRATIONS" -gt 0 ]; then
    echo "" >> "$GITHUB_STEP_SUMMARY"
    echo "⚠️  **Database migrations detected!** Run \`rails db:migrate\` after merging." >> "$GITHUB_STEP_SUMMARY"
  fi

  if [ "$BREAKING" -gt 0 ]; then
    echo "" >> "$GITHUB_STEP_SUMMARY"
    echo "⚠️  **Breaking changes detected!** Review carefully." >> "$GITHUB_STEP_SUMMARY"
  fi
fi
