# Copyright (C) 2012-2023 Zammad Foundation, https://zammad-foundation.org/

FactoryBot.define do
  factory :'ticket/state', aliases: %i[ticket_state] do
    name do
      # The following line ensures that the name generated by Faker
      # does not conflict with any existing names in the DB.
      Faker::Verb.unique.exclude(:past_participle, [], Ticket::State.pluck(:name))

      Faker::Verb.unique.past_participle
    end

    association :state_type, factory: :'ticket/state_type'
    updated_by_id { 1 }
    created_by_id { 1 }
  end
end
