name: build-docker-image

on:
  push:
    branches: [develop]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    env:
      DOCKER_GITHUB_REPOSITORY: "zammad-docker"
      DOCKER_IMAGES: "zammad"
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_REPOSITORY: "zammad"
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      REPO_USER: ${{ secrets.REPO_USER }}
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow
      - name: Build docker image
        run: .github/docker-image-build.sh
